// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息结构
type Message struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic       string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId int32                  `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Offset      int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Payload     []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Properties  map[string]string      `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp   int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Qos         int32                  `protobuf:"varint,8,opt,name=qos,proto3" json:"qos,omitempty"`
	// 生产端幂等支持
	ProducerId     string `protobuf:"bytes,9,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	SequenceNumber int64  `protobuf:"varint,10,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *Message) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *Message) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *Message) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type WriteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteMessageRequest) Reset() {
	*x = WriteMessageRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMessageRequest) ProtoMessage() {}

func (x *WriteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMessageRequest.ProtoReflect.Descriptor instead.
func (*WriteMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *WriteMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type WriteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteMessageResponse) Reset() {
	*x = WriteMessageResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteMessageResponse) ProtoMessage() {}

func (x *WriteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteMessageResponse.ProtoReflect.Descriptor instead.
func (*WriteMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *WriteMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WriteMessageResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId   int32                  `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessagesRequest) Reset() {
	*x = ReadMessagesRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessagesRequest) ProtoMessage() {}

func (x *ReadMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessagesRequest.ProtoReflect.Descriptor instead.
func (*ReadMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ReadMessagesRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ReadMessagesRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *ReadMessagesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessagesResponse) Reset() {
	*x = ReadMessagesResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessagesResponse) ProtoMessage() {}

func (x *ReadMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessagesResponse.ProtoReflect.Descriptor instead.
func (*ReadMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ReadMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ReadMessagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadMessagesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreatePartitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId   int32                  `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartitionRequest) Reset() {
	*x = CreatePartitionRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartitionRequest) ProtoMessage() {}

func (x *CreatePartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartitionRequest.ProtoReflect.Descriptor instead.
func (*CreatePartitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePartitionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreatePartitionRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type CreatePartitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartitionResponse) Reset() {
	*x = CreatePartitionResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartitionResponse) ProtoMessage() {}

func (x *CreatePartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartitionResponse.ProtoReflect.Descriptor instead.
func (*CreatePartitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePartitionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePartitionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetPartitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId   int32                  `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartitionRequest) Reset() {
	*x = GetPartitionRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartitionRequest) ProtoMessage() {}

func (x *GetPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartitionRequest.ProtoReflect.Descriptor instead.
func (*GetPartitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{7}
}

func (x *GetPartitionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetPartitionRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type PartitionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	NextOffset    int64                  `protobuf:"varint,3,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	MessageCount  int64                  `protobuf:"varint,4,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionInfo) Reset() {
	*x = PartitionInfo{}
	mi := &file_proto_storage_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionInfo) ProtoMessage() {}

func (x *PartitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionInfo.ProtoReflect.Descriptor instead.
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{8}
}

func (x *PartitionInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartitionInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PartitionInfo) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *PartitionInfo) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

type GetPartitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     *PartitionInfo         `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartitionResponse) Reset() {
	*x = GetPartitionResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartitionResponse) ProtoMessage() {}

func (x *GetPartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartitionResponse.ProtoReflect.Descriptor instead.
func (*GetPartitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{9}
}

func (x *GetPartitionResponse) GetPartition() *PartitionInfo {
	if x != nil {
		return x.Partition
	}
	return nil
}

func (x *GetPartitionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPartitionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId   int32                  `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOffsetRequest) Reset() {
	*x = UpdateOffsetRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOffsetRequest) ProtoMessage() {}

func (x *UpdateOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOffsetRequest.ProtoReflect.Descriptor instead.
func (*UpdateOffsetRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOffsetRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *UpdateOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *UpdateOffsetRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *UpdateOffsetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOffsetResponse) Reset() {
	*x = UpdateOffsetResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOffsetResponse) ProtoMessage() {}

func (x *UpdateOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOffsetResponse.ProtoReflect.Descriptor instead.
func (*UpdateOffsetResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateOffsetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateOffsetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId   int32                  `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetRequest) Reset() {
	*x = GetOffsetRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetRequest) ProtoMessage() {}

func (x *GetOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetOffsetRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{12}
}

func (x *GetOffsetRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *GetOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetOffsetRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type GetOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetResponse) Reset() {
	*x = GetOffsetResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetResponse) ProtoMessage() {}

func (x *GetOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetOffsetResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{13}
}

func (x *GetOffsetResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetOffsetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOffsetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListPartitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsRequest) Reset() {
	*x = ListPartitionsRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsRequest) ProtoMessage() {}

func (x *ListPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsRequest.ProtoReflect.Descriptor instead.
func (*ListPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{14}
}

func (x *ListPartitionsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ListPartitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*PartitionInfo       `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsResponse) Reset() {
	*x = ListPartitionsResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsResponse) ProtoMessage() {}

func (x *ListPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsResponse.ProtoReflect.Descriptor instead.
func (*ListPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{15}
}

func (x *ListPartitionsResponse) GetPartitions() []*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *ListPartitionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListPartitionsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SetTTLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTTLRequest) Reset() {
	*x = SetTTLRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTTLRequest) ProtoMessage() {}

func (x *SetTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTTLRequest.ProtoReflect.Descriptor instead.
func (*SetTTLRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{16}
}

func (x *SetTTLRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SetTTLRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetTTLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTTLResponse) Reset() {
	*x = SetTTLResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTTLResponse) ProtoMessage() {}

func (x *SetTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTTLResponse.ProtoReflect.Descriptor instead.
func (*SetTTLResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{17}
}

func (x *SetTTLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTTLResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ConsumerState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId         string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerGroup      string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic              string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	AssignedPartitions []int32                `protobuf:"varint,4,rep,packed,name=assigned_partitions,json=assignedPartitions,proto3" json:"assigned_partitions,omitempty"`
	LastHeartbeat      int64                  `protobuf:"varint,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsumerState) Reset() {
	*x = ConsumerState{}
	mi := &file_proto_storage_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerState) ProtoMessage() {}

func (x *ConsumerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerState.ProtoReflect.Descriptor instead.
func (*ConsumerState) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{18}
}

func (x *ConsumerState) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumerState) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *ConsumerState) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumerState) GetAssignedPartitions() []int32 {
	if x != nil {
		return x.AssignedPartitions
	}
	return nil
}

func (x *ConsumerState) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

type SaveConsumerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumer      *ConsumerState         `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConsumerRequest) Reset() {
	*x = SaveConsumerRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConsumerRequest) ProtoMessage() {}

func (x *SaveConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConsumerRequest.ProtoReflect.Descriptor instead.
func (*SaveConsumerRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{19}
}

func (x *SaveConsumerRequest) GetConsumer() *ConsumerState {
	if x != nil {
		return x.Consumer
	}
	return nil
}

type SaveConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConsumerResponse) Reset() {
	*x = SaveConsumerResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConsumerResponse) ProtoMessage() {}

func (x *SaveConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConsumerResponse.ProtoReflect.Descriptor instead.
func (*SaveConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{20}
}

func (x *SaveConsumerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveConsumerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetConsumersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumersRequest) Reset() {
	*x = GetConsumersRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumersRequest) ProtoMessage() {}

func (x *GetConsumersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumersRequest.ProtoReflect.Descriptor instead.
func (*GetConsumersRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{21}
}

func (x *GetConsumersRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *GetConsumersRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetConsumersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumers     []*ConsumerState       `protobuf:"bytes,1,rep,name=consumers,proto3" json:"consumers,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumersResponse) Reset() {
	*x = GetConsumersResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumersResponse) ProtoMessage() {}

func (x *GetConsumersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumersResponse.ProtoReflect.Descriptor instead.
func (*GetConsumersResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{22}
}

func (x *GetConsumersResponse) GetConsumers() []*ConsumerState {
	if x != nil {
		return x.Consumers
	}
	return nil
}

func (x *GetConsumersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConsumersResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeleteConsumerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConsumerRequest) Reset() {
	*x = DeleteConsumerRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConsumerRequest) ProtoMessage() {}

func (x *DeleteConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConsumerRequest.ProtoReflect.Descriptor instead.
func (*DeleteConsumerRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteConsumerRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *DeleteConsumerRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *DeleteConsumerRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type DeleteConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConsumerResponse) Reset() {
	*x = DeleteConsumerResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConsumerResponse) ProtoMessage() {}

func (x *DeleteConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConsumerResponse.ProtoReflect.Descriptor instead.
func (*DeleteConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteConsumerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteConsumerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateGroupAssignmentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup       string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic               string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionAssignment map[int32]string       `protobuf:"bytes,3,rep,name=partition_assignment,json=partitionAssignment,proto3" json:"partition_assignment,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // partitionID -> consumerID
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateGroupAssignmentRequest) Reset() {
	*x = UpdateGroupAssignmentRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupAssignmentRequest) ProtoMessage() {}

func (x *UpdateGroupAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupAssignmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateGroupAssignmentRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *UpdateGroupAssignmentRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *UpdateGroupAssignmentRequest) GetPartitionAssignment() map[int32]string {
	if x != nil {
		return x.PartitionAssignment
	}
	return nil
}

type UpdateGroupAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupAssignmentResponse) Reset() {
	*x = UpdateGroupAssignmentResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupAssignmentResponse) ProtoMessage() {}

func (x *UpdateGroupAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupAssignmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateGroupAssignmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateGroupAssignmentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetGroupAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupAssignmentRequest) Reset() {
	*x = GetGroupAssignmentRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupAssignmentRequest) ProtoMessage() {}

func (x *GetGroupAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetGroupAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{27}
}

func (x *GetGroupAssignmentRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *GetGroupAssignmentRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetGroupAssignmentResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PartitionAssignment map[int32]string       `protobuf:"bytes,1,rep,name=partition_assignment,json=partitionAssignment,proto3" json:"partition_assignment,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Success             bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetGroupAssignmentResponse) Reset() {
	*x = GetGroupAssignmentResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupAssignmentResponse) ProtoMessage() {}

func (x *GetGroupAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupAssignmentResponse.ProtoReflect.Descriptor instead.
func (*GetGroupAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{28}
}

func (x *GetGroupAssignmentResponse) GetPartitionAssignment() map[int32]string {
	if x != nil {
		return x.PartitionAssignment
	}
	return nil
}

func (x *GetGroupAssignmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetGroupAssignmentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_storage_storage_proto protoreflect.FileDescriptor

const file_proto_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/storage/storage.proto\x12\astorage\"\xff\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\x05R\vpartitionId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12@\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2 .storage.Message.PropertiesEntryR\n" +
	"properties\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03qos\x18\b \x01(\x05R\x03qos\x12\x1f\n" +
	"\vproducer_id\x18\t \x01(\tR\n" +
	"producerId\x12'\n" +
	"\x0fsequence_number\x18\n" +
	" \x01(\x03R\x0esequenceNumber\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x13WriteMessageRequest\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.storage.MessageR\amessage\"m\n" +
	"\x14WriteMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"|\n" +
	"\x13ReadMessagesRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x14ReadMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.storage.MessageR\bmessages\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"Q\n" +
	"\x16CreatePartitionRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\"X\n" +
	"\x17CreatePartitionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"N\n" +
	"\x13GetPartitionRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\"{\n" +
	"\rPartitionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1f\n" +
	"\vnext_offset\x18\x03 \x01(\x03R\n" +
	"nextOffset\x12#\n" +
	"\rmessage_count\x18\x04 \x01(\x03R\fmessageCount\"\x8b\x01\n" +
	"\x14GetPartitionResponse\x124\n" +
	"\tpartition\x18\x01 \x01(\v2\x16.storage.PartitionInfoR\tpartition\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x8d\x01\n" +
	"\x13UpdateOffsetRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\x05R\vpartitionId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"U\n" +
	"\x14UpdateOffsetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"r\n" +
	"\x10GetOffsetRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\x05R\vpartitionId\"j\n" +
	"\x11GetOffsetResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"-\n" +
	"\x15ListPartitionsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\x8f\x01\n" +
	"\x16ListPartitionsResponse\x126\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x16.storage.PartitionInfoR\n" +
	"partitions\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"F\n" +
	"\rSetTTLRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"O\n" +
	"\x0eSetTTLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xc5\x01\n" +
	"\rConsumerState\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12/\n" +
	"\x13assigned_partitions\x18\x04 \x03(\x05R\x12assignedPartitions\x12%\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\x03R\rlastHeartbeat\"I\n" +
	"\x13SaveConsumerRequest\x122\n" +
	"\bconsumer\x18\x01 \x01(\v2\x16.storage.ConsumerStateR\bconsumer\"U\n" +
	"\x14SaveConsumerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"R\n" +
	"\x13GetConsumersRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\x8b\x01\n" +
	"\x14GetConsumersResponse\x124\n" +
	"\tconsumers\x18\x01 \x03(\v2\x16.storage.ConsumerStateR\tconsumers\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"u\n" +
	"\x15DeleteConsumerRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"W\n" +
	"\x16DeleteConsumerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x96\x02\n" +
	"\x1cUpdateGroupAssignmentRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12q\n" +
	"\x14partition_assignment\x18\x03 \x03(\v2>.storage.UpdateGroupAssignmentRequest.PartitionAssignmentEntryR\x13partitionAssignment\x1aF\n" +
	"\x18PartitionAssignmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x1dUpdateGroupAssignmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"X\n" +
	"\x19GetGroupAssignmentRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\x94\x02\n" +
	"\x1aGetGroupAssignmentResponse\x12o\n" +
	"\x14partition_assignment\x18\x01 \x03(\v2<.storage.GetGroupAssignmentResponse.PartitionAssignmentEntryR\x13partitionAssignment\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x1aF\n" +
	"\x18PartitionAssignmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa0\b\n" +
	"\x0eStorageService\x12K\n" +
	"\fWriteMessage\x12\x1c.storage.WriteMessageRequest\x1a\x1d.storage.WriteMessageResponse\x12K\n" +
	"\fReadMessages\x12\x1c.storage.ReadMessagesRequest\x1a\x1d.storage.ReadMessagesResponse\x12T\n" +
	"\x0fCreatePartition\x12\x1f.storage.CreatePartitionRequest\x1a .storage.CreatePartitionResponse\x12K\n" +
	"\fGetPartition\x12\x1c.storage.GetPartitionRequest\x1a\x1d.storage.GetPartitionResponse\x12K\n" +
	"\fUpdateOffset\x12\x1c.storage.UpdateOffsetRequest\x1a\x1d.storage.UpdateOffsetResponse\x12B\n" +
	"\tGetOffset\x12\x19.storage.GetOffsetRequest\x1a\x1a.storage.GetOffsetResponse\x12Q\n" +
	"\x0eListPartitions\x12\x1e.storage.ListPartitionsRequest\x1a\x1f.storage.ListPartitionsResponse\x129\n" +
	"\x06SetTTL\x12\x16.storage.SetTTLRequest\x1a\x17.storage.SetTTLResponse\x12K\n" +
	"\fSaveConsumer\x12\x1c.storage.SaveConsumerRequest\x1a\x1d.storage.SaveConsumerResponse\x12K\n" +
	"\fGetConsumers\x12\x1c.storage.GetConsumersRequest\x1a\x1d.storage.GetConsumersResponse\x12Q\n" +
	"\x0eDeleteConsumer\x12\x1e.storage.DeleteConsumerRequest\x1a\x1f.storage.DeleteConsumerResponse\x12f\n" +
	"\x15UpdateGroupAssignment\x12%.storage.UpdateGroupAssignmentRequest\x1a&.storage.UpdateGroupAssignmentResponse\x12]\n" +
	"\x12GetGroupAssignment\x12\".storage.GetGroupAssignmentRequest\x1a#.storage.GetGroupAssignmentResponseB/Z-github.com/chowyu12/gmq/proto/storage;storageb\x06proto3"

var (
	file_proto_storage_storage_proto_rawDescOnce sync.Once
	file_proto_storage_storage_proto_rawDescData []byte
)

func file_proto_storage_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_storage_proto_rawDesc), len(file_proto_storage_storage_proto_rawDesc)))
	})
	return file_proto_storage_storage_proto_rawDescData
}

var file_proto_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_storage_storage_proto_goTypes = []any{
	(*Message)(nil),                       // 0: storage.Message
	(*WriteMessageRequest)(nil),           // 1: storage.WriteMessageRequest
	(*WriteMessageResponse)(nil),          // 2: storage.WriteMessageResponse
	(*ReadMessagesRequest)(nil),           // 3: storage.ReadMessagesRequest
	(*ReadMessagesResponse)(nil),          // 4: storage.ReadMessagesResponse
	(*CreatePartitionRequest)(nil),        // 5: storage.CreatePartitionRequest
	(*CreatePartitionResponse)(nil),       // 6: storage.CreatePartitionResponse
	(*GetPartitionRequest)(nil),           // 7: storage.GetPartitionRequest
	(*PartitionInfo)(nil),                 // 8: storage.PartitionInfo
	(*GetPartitionResponse)(nil),          // 9: storage.GetPartitionResponse
	(*UpdateOffsetRequest)(nil),           // 10: storage.UpdateOffsetRequest
	(*UpdateOffsetResponse)(nil),          // 11: storage.UpdateOffsetResponse
	(*GetOffsetRequest)(nil),              // 12: storage.GetOffsetRequest
	(*GetOffsetResponse)(nil),             // 13: storage.GetOffsetResponse
	(*ListPartitionsRequest)(nil),         // 14: storage.ListPartitionsRequest
	(*ListPartitionsResponse)(nil),        // 15: storage.ListPartitionsResponse
	(*SetTTLRequest)(nil),                 // 16: storage.SetTTLRequest
	(*SetTTLResponse)(nil),                // 17: storage.SetTTLResponse
	(*ConsumerState)(nil),                 // 18: storage.ConsumerState
	(*SaveConsumerRequest)(nil),           // 19: storage.SaveConsumerRequest
	(*SaveConsumerResponse)(nil),          // 20: storage.SaveConsumerResponse
	(*GetConsumersRequest)(nil),           // 21: storage.GetConsumersRequest
	(*GetConsumersResponse)(nil),          // 22: storage.GetConsumersResponse
	(*DeleteConsumerRequest)(nil),         // 23: storage.DeleteConsumerRequest
	(*DeleteConsumerResponse)(nil),        // 24: storage.DeleteConsumerResponse
	(*UpdateGroupAssignmentRequest)(nil),  // 25: storage.UpdateGroupAssignmentRequest
	(*UpdateGroupAssignmentResponse)(nil), // 26: storage.UpdateGroupAssignmentResponse
	(*GetGroupAssignmentRequest)(nil),     // 27: storage.GetGroupAssignmentRequest
	(*GetGroupAssignmentResponse)(nil),    // 28: storage.GetGroupAssignmentResponse
	nil,                                   // 29: storage.Message.PropertiesEntry
	nil,                                   // 30: storage.UpdateGroupAssignmentRequest.PartitionAssignmentEntry
	nil,                                   // 31: storage.GetGroupAssignmentResponse.PartitionAssignmentEntry
}
var file_proto_storage_storage_proto_depIdxs = []int32{
	29, // 0: storage.Message.properties:type_name -> storage.Message.PropertiesEntry
	0,  // 1: storage.WriteMessageRequest.message:type_name -> storage.Message
	0,  // 2: storage.ReadMessagesResponse.messages:type_name -> storage.Message
	8,  // 3: storage.GetPartitionResponse.partition:type_name -> storage.PartitionInfo
	8,  // 4: storage.ListPartitionsResponse.partitions:type_name -> storage.PartitionInfo
	18, // 5: storage.SaveConsumerRequest.consumer:type_name -> storage.ConsumerState
	18, // 6: storage.GetConsumersResponse.consumers:type_name -> storage.ConsumerState
	30, // 7: storage.UpdateGroupAssignmentRequest.partition_assignment:type_name -> storage.UpdateGroupAssignmentRequest.PartitionAssignmentEntry
	31, // 8: storage.GetGroupAssignmentResponse.partition_assignment:type_name -> storage.GetGroupAssignmentResponse.PartitionAssignmentEntry
	1,  // 9: storage.StorageService.WriteMessage:input_type -> storage.WriteMessageRequest
	3,  // 10: storage.StorageService.ReadMessages:input_type -> storage.ReadMessagesRequest
	5,  // 11: storage.StorageService.CreatePartition:input_type -> storage.CreatePartitionRequest
	7,  // 12: storage.StorageService.GetPartition:input_type -> storage.GetPartitionRequest
	10, // 13: storage.StorageService.UpdateOffset:input_type -> storage.UpdateOffsetRequest
	12, // 14: storage.StorageService.GetOffset:input_type -> storage.GetOffsetRequest
	14, // 15: storage.StorageService.ListPartitions:input_type -> storage.ListPartitionsRequest
	16, // 16: storage.StorageService.SetTTL:input_type -> storage.SetTTLRequest
	19, // 17: storage.StorageService.SaveConsumer:input_type -> storage.SaveConsumerRequest
	21, // 18: storage.StorageService.GetConsumers:input_type -> storage.GetConsumersRequest
	23, // 19: storage.StorageService.DeleteConsumer:input_type -> storage.DeleteConsumerRequest
	25, // 20: storage.StorageService.UpdateGroupAssignment:input_type -> storage.UpdateGroupAssignmentRequest
	27, // 21: storage.StorageService.GetGroupAssignment:input_type -> storage.GetGroupAssignmentRequest
	2,  // 22: storage.StorageService.WriteMessage:output_type -> storage.WriteMessageResponse
	4,  // 23: storage.StorageService.ReadMessages:output_type -> storage.ReadMessagesResponse
	6,  // 24: storage.StorageService.CreatePartition:output_type -> storage.CreatePartitionResponse
	9,  // 25: storage.StorageService.GetPartition:output_type -> storage.GetPartitionResponse
	11, // 26: storage.StorageService.UpdateOffset:output_type -> storage.UpdateOffsetResponse
	13, // 27: storage.StorageService.GetOffset:output_type -> storage.GetOffsetResponse
	15, // 28: storage.StorageService.ListPartitions:output_type -> storage.ListPartitionsResponse
	17, // 29: storage.StorageService.SetTTL:output_type -> storage.SetTTLResponse
	20, // 30: storage.StorageService.SaveConsumer:output_type -> storage.SaveConsumerResponse
	22, // 31: storage.StorageService.GetConsumers:output_type -> storage.GetConsumersResponse
	24, // 32: storage.StorageService.DeleteConsumer:output_type -> storage.DeleteConsumerResponse
	26, // 33: storage.StorageService.UpdateGroupAssignment:output_type -> storage.UpdateGroupAssignmentResponse
	28, // 34: storage.StorageService.GetGroupAssignment:output_type -> storage.GetGroupAssignmentResponse
	22, // [22:35] is the sub-list for method output_type
	9,  // [9:22] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_storage_storage_proto_init() }
func file_proto_storage_storage_proto_init() {
	if File_proto_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_storage_proto_rawDesc), len(file_proto_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_storage_proto_depIdxs,
		MessageInfos:      file_proto_storage_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_storage_proto = out.File
	file_proto_storage_storage_proto_goTypes = nil
	file_proto_storage_storage_proto_depIdxs = nil
}
