// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/storage/storage.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_WriteMessages_FullMethodName         = "/storage.StorageService/WriteMessages"
	StorageService_ReadMessages_FullMethodName          = "/storage.StorageService/ReadMessages"
	StorageService_CreatePartition_FullMethodName       = "/storage.StorageService/CreatePartition"
	StorageService_GetPartition_FullMethodName          = "/storage.StorageService/GetPartition"
	StorageService_UpdateOffset_FullMethodName          = "/storage.StorageService/UpdateOffset"
	StorageService_GetOffset_FullMethodName             = "/storage.StorageService/GetOffset"
	StorageService_ListPartitions_FullMethodName        = "/storage.StorageService/ListPartitions"
	StorageService_SetTTL_FullMethodName                = "/storage.StorageService/SetTTL"
	StorageService_SaveConsumer_FullMethodName          = "/storage.StorageService/SaveConsumer"
	StorageService_GetConsumers_FullMethodName          = "/storage.StorageService/GetConsumers"
	StorageService_DeleteConsumer_FullMethodName        = "/storage.StorageService/DeleteConsumer"
	StorageService_UpdateGroupAssignment_FullMethodName = "/storage.StorageService/UpdateGroupAssignment"
	StorageService_GetGroupAssignment_FullMethodName    = "/storage.StorageService/GetGroupAssignment"
	StorageService_FetchMessages_FullMethodName         = "/storage.StorageService/FetchMessages"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Storage Service - Storage service interface
type StorageServiceClient interface {
	// --- Message interface ---
	WriteMessages(ctx context.Context, in *WriteMessagesRequest, opts ...grpc.CallOption) (*WriteMessagesResponse, error)
	ReadMessages(ctx context.Context, in *ReadMessagesRequest, opts ...grpc.CallOption) (*ReadMessagesResponse, error)
	CreatePartition(ctx context.Context, in *CreatePartitionRequest, opts ...grpc.CallOption) (*CreatePartitionResponse, error)
	GetPartition(ctx context.Context, in *GetPartitionRequest, opts ...grpc.CallOption) (*GetPartitionResponse, error)
	UpdateOffset(ctx context.Context, in *UpdateOffsetRequest, opts ...grpc.CallOption) (*UpdateOffsetResponse, error)
	GetOffset(ctx context.Context, in *GetOffsetRequest, opts ...grpc.CallOption) (*GetOffsetResponse, error)
	ListPartitions(ctx context.Context, in *ListPartitionsRequest, opts ...grpc.CallOption) (*ListPartitionsResponse, error)
	SetTTL(ctx context.Context, in *SetTTLRequest, opts ...grpc.CallOption) (*SetTTLResponse, error)
	// Save/update consumer information
	SaveConsumer(ctx context.Context, in *SaveConsumerRequest, opts ...grpc.CallOption) (*SaveConsumerResponse, error)
	// Get all consumers in a consumer group
	GetConsumers(ctx context.Context, in *GetConsumersRequest, opts ...grpc.CallOption) (*GetConsumersResponse, error)
	// Delete consumer
	DeleteConsumer(ctx context.Context, in *DeleteConsumerRequest, opts ...grpc.CallOption) (*DeleteConsumerResponse, error)
	// Update consumer group assignment information
	UpdateGroupAssignment(ctx context.Context, in *UpdateGroupAssignmentRequest, opts ...grpc.CallOption) (*UpdateGroupAssignmentResponse, error)
	// Get consumer group assignment information
	GetGroupAssignment(ctx context.Context, in *GetGroupAssignmentRequest, opts ...grpc.CallOption) (*GetGroupAssignmentResponse, error)
	// Atomic fetch: get current offset -> read messages -> update offset (atomic operation)
	FetchMessages(ctx context.Context, in *FetchMessagesRequest, opts ...grpc.CallOption) (*FetchMessagesResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) WriteMessages(ctx context.Context, in *WriteMessagesRequest, opts ...grpc.CallOption) (*WriteMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteMessagesResponse)
	err := c.cc.Invoke(ctx, StorageService_WriteMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ReadMessages(ctx context.Context, in *ReadMessagesRequest, opts ...grpc.CallOption) (*ReadMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadMessagesResponse)
	err := c.cc.Invoke(ctx, StorageService_ReadMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreatePartition(ctx context.Context, in *CreatePartitionRequest, opts ...grpc.CallOption) (*CreatePartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePartitionResponse)
	err := c.cc.Invoke(ctx, StorageService_CreatePartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetPartition(ctx context.Context, in *GetPartitionRequest, opts ...grpc.CallOption) (*GetPartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartitionResponse)
	err := c.cc.Invoke(ctx, StorageService_GetPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UpdateOffset(ctx context.Context, in *UpdateOffsetRequest, opts ...grpc.CallOption) (*UpdateOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOffsetResponse)
	err := c.cc.Invoke(ctx, StorageService_UpdateOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetOffset(ctx context.Context, in *GetOffsetRequest, opts ...grpc.CallOption) (*GetOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOffsetResponse)
	err := c.cc.Invoke(ctx, StorageService_GetOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListPartitions(ctx context.Context, in *ListPartitionsRequest, opts ...grpc.CallOption) (*ListPartitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartitionsResponse)
	err := c.cc.Invoke(ctx, StorageService_ListPartitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetTTL(ctx context.Context, in *SetTTLRequest, opts ...grpc.CallOption) (*SetTTLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTTLResponse)
	err := c.cc.Invoke(ctx, StorageService_SetTTL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SaveConsumer(ctx context.Context, in *SaveConsumerRequest, opts ...grpc.CallOption) (*SaveConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConsumerResponse)
	err := c.cc.Invoke(ctx, StorageService_SaveConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetConsumers(ctx context.Context, in *GetConsumersRequest, opts ...grpc.CallOption) (*GetConsumersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConsumersResponse)
	err := c.cc.Invoke(ctx, StorageService_GetConsumers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteConsumer(ctx context.Context, in *DeleteConsumerRequest, opts ...grpc.CallOption) (*DeleteConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConsumerResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UpdateGroupAssignment(ctx context.Context, in *UpdateGroupAssignmentRequest, opts ...grpc.CallOption) (*UpdateGroupAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGroupAssignmentResponse)
	err := c.cc.Invoke(ctx, StorageService_UpdateGroupAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetGroupAssignment(ctx context.Context, in *GetGroupAssignmentRequest, opts ...grpc.CallOption) (*GetGroupAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupAssignmentResponse)
	err := c.cc.Invoke(ctx, StorageService_GetGroupAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) FetchMessages(ctx context.Context, in *FetchMessagesRequest, opts ...grpc.CallOption) (*FetchMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchMessagesResponse)
	err := c.cc.Invoke(ctx, StorageService_FetchMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// Storage Service - Storage service interface
type StorageServiceServer interface {
	// --- Message interface ---
	WriteMessages(context.Context, *WriteMessagesRequest) (*WriteMessagesResponse, error)
	ReadMessages(context.Context, *ReadMessagesRequest) (*ReadMessagesResponse, error)
	CreatePartition(context.Context, *CreatePartitionRequest) (*CreatePartitionResponse, error)
	GetPartition(context.Context, *GetPartitionRequest) (*GetPartitionResponse, error)
	UpdateOffset(context.Context, *UpdateOffsetRequest) (*UpdateOffsetResponse, error)
	GetOffset(context.Context, *GetOffsetRequest) (*GetOffsetResponse, error)
	ListPartitions(context.Context, *ListPartitionsRequest) (*ListPartitionsResponse, error)
	SetTTL(context.Context, *SetTTLRequest) (*SetTTLResponse, error)
	// Save/update consumer information
	SaveConsumer(context.Context, *SaveConsumerRequest) (*SaveConsumerResponse, error)
	// Get all consumers in a consumer group
	GetConsumers(context.Context, *GetConsumersRequest) (*GetConsumersResponse, error)
	// Delete consumer
	DeleteConsumer(context.Context, *DeleteConsumerRequest) (*DeleteConsumerResponse, error)
	// Update consumer group assignment information
	UpdateGroupAssignment(context.Context, *UpdateGroupAssignmentRequest) (*UpdateGroupAssignmentResponse, error)
	// Get consumer group assignment information
	GetGroupAssignment(context.Context, *GetGroupAssignmentRequest) (*GetGroupAssignmentResponse, error)
	// Atomic fetch: get current offset -> read messages -> update offset (atomic operation)
	FetchMessages(context.Context, *FetchMessagesRequest) (*FetchMessagesResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) WriteMessages(context.Context, *WriteMessagesRequest) (*WriteMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteMessages not implemented")
}
func (UnimplementedStorageServiceServer) ReadMessages(context.Context, *ReadMessagesRequest) (*ReadMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadMessages not implemented")
}
func (UnimplementedStorageServiceServer) CreatePartition(context.Context, *CreatePartitionRequest) (*CreatePartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePartition not implemented")
}
func (UnimplementedStorageServiceServer) GetPartition(context.Context, *GetPartitionRequest) (*GetPartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartition not implemented")
}
func (UnimplementedStorageServiceServer) UpdateOffset(context.Context, *UpdateOffsetRequest) (*UpdateOffsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOffset not implemented")
}
func (UnimplementedStorageServiceServer) GetOffset(context.Context, *GetOffsetRequest) (*GetOffsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOffset not implemented")
}
func (UnimplementedStorageServiceServer) ListPartitions(context.Context, *ListPartitionsRequest) (*ListPartitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPartitions not implemented")
}
func (UnimplementedStorageServiceServer) SetTTL(context.Context, *SetTTLRequest) (*SetTTLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTTL not implemented")
}
func (UnimplementedStorageServiceServer) SaveConsumer(context.Context, *SaveConsumerRequest) (*SaveConsumerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveConsumer not implemented")
}
func (UnimplementedStorageServiceServer) GetConsumers(context.Context, *GetConsumersRequest) (*GetConsumersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumers not implemented")
}
func (UnimplementedStorageServiceServer) DeleteConsumer(context.Context, *DeleteConsumerRequest) (*DeleteConsumerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConsumer not implemented")
}
func (UnimplementedStorageServiceServer) UpdateGroupAssignment(context.Context, *UpdateGroupAssignmentRequest) (*UpdateGroupAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupAssignment not implemented")
}
func (UnimplementedStorageServiceServer) GetGroupAssignment(context.Context, *GetGroupAssignmentRequest) (*GetGroupAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupAssignment not implemented")
}
func (UnimplementedStorageServiceServer) FetchMessages(context.Context, *FetchMessagesRequest) (*FetchMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMessages not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_WriteMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).WriteMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_WriteMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).WriteMessages(ctx, req.(*WriteMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ReadMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ReadMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ReadMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ReadMessages(ctx, req.(*ReadMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreatePartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreatePartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreatePartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreatePartition(ctx, req.(*CreatePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetPartition(ctx, req.(*GetPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UpdateOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UpdateOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_UpdateOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UpdateOffset(ctx, req.(*UpdateOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetOffset(ctx, req.(*GetOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListPartitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListPartitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListPartitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListPartitions(ctx, req.(*ListPartitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SetTTL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetTTL(ctx, req.(*SetTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SaveConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SaveConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SaveConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SaveConsumer(ctx, req.(*SaveConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetConsumers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsumersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetConsumers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetConsumers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetConsumers(ctx, req.(*GetConsumersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteConsumer(ctx, req.(*DeleteConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UpdateGroupAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UpdateGroupAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_UpdateGroupAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UpdateGroupAssignment(ctx, req.(*UpdateGroupAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetGroupAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetGroupAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetGroupAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetGroupAssignment(ctx, req.(*GetGroupAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_FetchMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).FetchMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_FetchMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).FetchMessages(ctx, req.(*FetchMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteMessages",
			Handler:    _StorageService_WriteMessages_Handler,
		},
		{
			MethodName: "ReadMessages",
			Handler:    _StorageService_ReadMessages_Handler,
		},
		{
			MethodName: "CreatePartition",
			Handler:    _StorageService_CreatePartition_Handler,
		},
		{
			MethodName: "GetPartition",
			Handler:    _StorageService_GetPartition_Handler,
		},
		{
			MethodName: "UpdateOffset",
			Handler:    _StorageService_UpdateOffset_Handler,
		},
		{
			MethodName: "GetOffset",
			Handler:    _StorageService_GetOffset_Handler,
		},
		{
			MethodName: "ListPartitions",
			Handler:    _StorageService_ListPartitions_Handler,
		},
		{
			MethodName: "SetTTL",
			Handler:    _StorageService_SetTTL_Handler,
		},
		{
			MethodName: "SaveConsumer",
			Handler:    _StorageService_SaveConsumer_Handler,
		},
		{
			MethodName: "GetConsumers",
			Handler:    _StorageService_GetConsumers_Handler,
		},
		{
			MethodName: "DeleteConsumer",
			Handler:    _StorageService_DeleteConsumer_Handler,
		},
		{
			MethodName: "UpdateGroupAssignment",
			Handler:    _StorageService_UpdateGroupAssignment_Handler,
		},
		{
			MethodName: "GetGroupAssignment",
			Handler:    _StorageService_GetGroupAssignment_Handler,
		},
		{
			MethodName: "FetchMessages",
			Handler:    _StorageService_FetchMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/storage/storage.proto",
}
