// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/gmq.proto

package gmq

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	// 发布消息请求
	MessageType_MESSAGE_TYPE_PUBLISH_REQUEST MessageType = 1
	// 发布消息响应
	MessageType_MESSAGE_TYPE_PUBLISH_RESPONSE MessageType = 2
	// 订阅请求
	MessageType_MESSAGE_TYPE_SUBSCRIBE_REQUEST MessageType = 3
	// 订阅响应
	MessageType_MESSAGE_TYPE_SUBSCRIBE_RESPONSE MessageType = 4
	// 消费消息推送
	MessageType_MESSAGE_TYPE_CONSUME_MESSAGE MessageType = 5
	// 消息确认请求
	MessageType_MESSAGE_TYPE_ACK_REQUEST MessageType = 6
	// 消息确认响应
	MessageType_MESSAGE_TYPE_ACK_RESPONSE MessageType = 7
	// 心跳请求
	MessageType_MESSAGE_TYPE_HEARTBEAT_REQUEST MessageType = 8
	// 心跳响应
	MessageType_MESSAGE_TYPE_HEARTBEAT_RESPONSE MessageType = 9
	// 错误响应
	MessageType_MESSAGE_TYPE_ERROR_RESPONSE MessageType = 10
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_PUBLISH_REQUEST",
		2:  "MESSAGE_TYPE_PUBLISH_RESPONSE",
		3:  "MESSAGE_TYPE_SUBSCRIBE_REQUEST",
		4:  "MESSAGE_TYPE_SUBSCRIBE_RESPONSE",
		5:  "MESSAGE_TYPE_CONSUME_MESSAGE",
		6:  "MESSAGE_TYPE_ACK_REQUEST",
		7:  "MESSAGE_TYPE_ACK_RESPONSE",
		8:  "MESSAGE_TYPE_HEARTBEAT_REQUEST",
		9:  "MESSAGE_TYPE_HEARTBEAT_RESPONSE",
		10: "MESSAGE_TYPE_ERROR_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":        0,
		"MESSAGE_TYPE_PUBLISH_REQUEST":    1,
		"MESSAGE_TYPE_PUBLISH_RESPONSE":   2,
		"MESSAGE_TYPE_SUBSCRIBE_REQUEST":  3,
		"MESSAGE_TYPE_SUBSCRIBE_RESPONSE": 4,
		"MESSAGE_TYPE_CONSUME_MESSAGE":    5,
		"MESSAGE_TYPE_ACK_REQUEST":        6,
		"MESSAGE_TYPE_ACK_RESPONSE":       7,
		"MESSAGE_TYPE_HEARTBEAT_REQUEST":  8,
		"MESSAGE_TYPE_HEARTBEAT_RESPONSE": 9,
		"MESSAGE_TYPE_ERROR_RESPONSE":     10,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gmq_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_gmq_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{0}
}

// QoS 级别
type QoS int32

const (
	QoS_QOS_UNSPECIFIED QoS = 0
	// 至多一次
	QoS_QOS_AT_MOST_ONCE QoS = 1
	// 至少一次
	QoS_QOS_AT_LEAST_ONCE QoS = 2
)

// Enum value maps for QoS.
var (
	QoS_name = map[int32]string{
		0: "QOS_UNSPECIFIED",
		1: "QOS_AT_MOST_ONCE",
		2: "QOS_AT_LEAST_ONCE",
	}
	QoS_value = map[string]int32{
		"QOS_UNSPECIFIED":   0,
		"QOS_AT_MOST_ONCE":  1,
		"QOS_AT_LEAST_ONCE": 2,
	}
)

func (x QoS) Enum() *QoS {
	p := new(QoS)
	*p = x
	return p
}

func (x QoS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QoS) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gmq_proto_enumTypes[1].Descriptor()
}

func (QoS) Type() protoreflect.EnumType {
	return &file_proto_gmq_proto_enumTypes[1]
}

func (x QoS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QoS.Descriptor instead.
func (QoS) EnumDescriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{1}
}

// 流消息封装
type StreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息类型
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=gmq.MessageType" json:"type,omitempty"`
	// 具体消息内容（根据type选择对应字段）
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamMessage_PublishReq
	//	*StreamMessage_PublishResp
	//	*StreamMessage_SubscribeReq
	//	*StreamMessage_SubscribeResp
	//	*StreamMessage_ConsumeMsg
	//	*StreamMessage_AckReq
	//	*StreamMessage_AckResp
	//	*StreamMessage_HeartbeatReq
	//	*StreamMessage_HeartbeatResp
	//	*StreamMessage_ErrorResp
	Payload       isStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_proto_gmq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{0}
}

func (x *StreamMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *StreamMessage) GetPayload() isStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamMessage) GetPublishReq() *PublishRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_PublishReq); ok {
			return x.PublishReq
		}
	}
	return nil
}

func (x *StreamMessage) GetPublishResp() *PublishResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_PublishResp); ok {
			return x.PublishResp
		}
	}
	return nil
}

func (x *StreamMessage) GetSubscribeReq() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_SubscribeReq); ok {
			return x.SubscribeReq
		}
	}
	return nil
}

func (x *StreamMessage) GetSubscribeResp() *SubscribeResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_SubscribeResp); ok {
			return x.SubscribeResp
		}
	}
	return nil
}

func (x *StreamMessage) GetConsumeMsg() *ConsumeMessage {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_ConsumeMsg); ok {
			return x.ConsumeMsg
		}
	}
	return nil
}

func (x *StreamMessage) GetAckReq() *AckRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_AckReq); ok {
			return x.AckReq
		}
	}
	return nil
}

func (x *StreamMessage) GetAckResp() *AckResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_AckResp); ok {
			return x.AckResp
		}
	}
	return nil
}

func (x *StreamMessage) GetHeartbeatReq() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_HeartbeatReq); ok {
			return x.HeartbeatReq
		}
	}
	return nil
}

func (x *StreamMessage) GetHeartbeatResp() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_HeartbeatResp); ok {
			return x.HeartbeatResp
		}
	}
	return nil
}

func (x *StreamMessage) GetErrorResp() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_ErrorResp); ok {
			return x.ErrorResp
		}
	}
	return nil
}

type isStreamMessage_Payload interface {
	isStreamMessage_Payload()
}

type StreamMessage_PublishReq struct {
	PublishReq *PublishRequest `protobuf:"bytes,2,opt,name=publish_req,json=publishReq,proto3,oneof"`
}

type StreamMessage_PublishResp struct {
	PublishResp *PublishResponse `protobuf:"bytes,3,opt,name=publish_resp,json=publishResp,proto3,oneof"`
}

type StreamMessage_SubscribeReq struct {
	SubscribeReq *SubscribeRequest `protobuf:"bytes,4,opt,name=subscribe_req,json=subscribeReq,proto3,oneof"`
}

type StreamMessage_SubscribeResp struct {
	SubscribeResp *SubscribeResponse `protobuf:"bytes,5,opt,name=subscribe_resp,json=subscribeResp,proto3,oneof"`
}

type StreamMessage_ConsumeMsg struct {
	ConsumeMsg *ConsumeMessage `protobuf:"bytes,6,opt,name=consume_msg,json=consumeMsg,proto3,oneof"`
}

type StreamMessage_AckReq struct {
	AckReq *AckRequest `protobuf:"bytes,7,opt,name=ack_req,json=ackReq,proto3,oneof"`
}

type StreamMessage_AckResp struct {
	AckResp *AckResponse `protobuf:"bytes,8,opt,name=ack_resp,json=ackResp,proto3,oneof"`
}

type StreamMessage_HeartbeatReq struct {
	HeartbeatReq *HeartbeatRequest `protobuf:"bytes,9,opt,name=heartbeat_req,json=heartbeatReq,proto3,oneof"`
}

type StreamMessage_HeartbeatResp struct {
	HeartbeatResp *HeartbeatResponse `protobuf:"bytes,10,opt,name=heartbeat_resp,json=heartbeatResp,proto3,oneof"`
}

type StreamMessage_ErrorResp struct {
	ErrorResp *ErrorResponse `protobuf:"bytes,11,opt,name=error_resp,json=errorResp,proto3,oneof"`
}

func (*StreamMessage_PublishReq) isStreamMessage_Payload() {}

func (*StreamMessage_PublishResp) isStreamMessage_Payload() {}

func (*StreamMessage_SubscribeReq) isStreamMessage_Payload() {}

func (*StreamMessage_SubscribeResp) isStreamMessage_Payload() {}

func (*StreamMessage_ConsumeMsg) isStreamMessage_Payload() {}

func (*StreamMessage_AckReq) isStreamMessage_Payload() {}

func (*StreamMessage_AckResp) isStreamMessage_Payload() {}

func (*StreamMessage_HeartbeatReq) isStreamMessage_Payload() {}

func (*StreamMessage_HeartbeatResp) isStreamMessage_Payload() {}

func (*StreamMessage_ErrorResp) isStreamMessage_Payload() {}

// 发布消息请求
type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Topic 名称
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// 分区键（用于确定分区）
	PartitionKey string `protobuf:"bytes,3,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	// 指定分区ID（可选，优先级高于partition_key）
	PartitionId int32 `protobuf:"varint,4,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// 消息体
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// 消息属性
	Properties map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// QoS 级别
	Qos           QoS `protobuf:"varint,7,opt,name=qos,proto3,enum=gmq.QoS" json:"qos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_gmq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *PublishRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *PublishRequest) GetQos() QoS {
	if x != nil {
		return x.Qos
	}
	return QoS_QOS_UNSPECIFIED
}

// 发布消息响应
type PublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 是否成功
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 消息ID
	MessageId string `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Topic 名称
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// 实际分区ID
	PartitionId int32 `protobuf:"varint,5,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// 错误信息
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_gmq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PublishResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishResponse) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PublishResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 订阅请求
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Topic 名称
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// 消费组名称
	ConsumerGroup string `protobuf:"bytes,3,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	// 消费者ID
	ConsumerId string `protobuf:"bytes,4,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// QoS 级别
	Qos QoS `protobuf:"varint,5,opt,name=qos,proto3,enum=gmq.QoS" json:"qos,omitempty"`
	// 订阅的分区列表（为空则订阅所有分区）
	Partitions []int32 `protobuf:"varint,6,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`
	// 拉取间隔（毫秒），可选
	PullIntervalMs int32 `protobuf:"varint,7,opt,name=pull_interval_ms,json=pullIntervalMs,proto3" json:"pull_interval_ms,omitempty"`
	// 客户端标识，可选
	ClientId      string `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_gmq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *SubscribeRequest) GetQos() QoS {
	if x != nil {
		return x.Qos
	}
	return QoS_QOS_UNSPECIFIED
}

func (x *SubscribeRequest) GetPartitions() []int32 {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *SubscribeRequest) GetPullIntervalMs() int32 {
	if x != nil {
		return x.PullIntervalMs
	}
	return 0
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// 手动创建 Topic 请求
type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions    int32                  `protobuf:"varint,2,opt,name=partitions,proto3" json:"partitions,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 新增：过期时间（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_proto_gmq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateTopicRequest) GetPartitions() int32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *CreateTopicRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_proto_gmq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTopicResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 订阅响应
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 是否成功
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 分配的分区列表
	AssignedPartitions []int32 `protobuf:"varint,3,rep,packed,name=assigned_partitions,json=assignedPartitions,proto3" json:"assigned_partitions,omitempty"`
	// 错误信息
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_proto_gmq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscribeResponse) GetAssignedPartitions() []int32 {
	if x != nil {
		return x.AssignedPartitions
	}
	return nil
}

func (x *SubscribeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 消费消息
type ConsumeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息ID
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Topic 名称
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// 分区ID
	PartitionId int32 `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// 偏移量
	Offset int64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// 消息体
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// 消息属性
	Properties map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 时间戳
	Timestamp int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// QoS 级别
	Qos           QoS `protobuf:"varint,8,opt,name=qos,proto3,enum=gmq.QoS" json:"qos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeMessage) Reset() {
	*x = ConsumeMessage{}
	mi := &file_proto_gmq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeMessage) ProtoMessage() {}

func (x *ConsumeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeMessage.ProtoReflect.Descriptor instead.
func (*ConsumeMessage) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{7}
}

func (x *ConsumeMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ConsumeMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeMessage) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *ConsumeMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConsumeMessage) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ConsumeMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConsumeMessage) GetQos() QoS {
	if x != nil {
		return x.Qos
	}
	return QoS_QOS_UNSPECIFIED
}

// 消息确认请求
type AckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 消息ID
	MessageId string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Topic 名称
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// 分区ID
	PartitionId int32 `protobuf:"varint,4,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// 消费组
	ConsumerGroup string `protobuf:"bytes,5,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	// 消费者ID
	ConsumerId string `protobuf:"bytes,6,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// 偏移量
	Offset        int64 `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_gmq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{8}
}

func (x *AckRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AckRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AckRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *AckRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *AckRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *AckRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// 消息确认响应
type AckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 是否成功
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_gmq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{9}
}

func (x *AckResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 心跳请求
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消费者ID
	ConsumerId string `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// 消费组
	ConsumerGroup string `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_gmq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *HeartbeatRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

// 心跳响应
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_gmq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 错误响应
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误信息
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_gmq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_gmq_proto protoreflect.FileDescriptor

const file_proto_gmq_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/gmq.proto\x12\x03gmq\"\xf9\x04\n" +
	"\rStreamMessage\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.gmq.MessageTypeR\x04type\x126\n" +
	"\vpublish_req\x18\x02 \x01(\v2\x13.gmq.PublishRequestH\x00R\n" +
	"publishReq\x129\n" +
	"\fpublish_resp\x18\x03 \x01(\v2\x14.gmq.PublishResponseH\x00R\vpublishResp\x12<\n" +
	"\rsubscribe_req\x18\x04 \x01(\v2\x15.gmq.SubscribeRequestH\x00R\fsubscribeReq\x12?\n" +
	"\x0esubscribe_resp\x18\x05 \x01(\v2\x16.gmq.SubscribeResponseH\x00R\rsubscribeResp\x126\n" +
	"\vconsume_msg\x18\x06 \x01(\v2\x13.gmq.ConsumeMessageH\x00R\n" +
	"consumeMsg\x12*\n" +
	"\aack_req\x18\a \x01(\v2\x0f.gmq.AckRequestH\x00R\x06ackReq\x12-\n" +
	"\back_resp\x18\b \x01(\v2\x10.gmq.AckResponseH\x00R\aackResp\x12<\n" +
	"\rheartbeat_req\x18\t \x01(\v2\x15.gmq.HeartbeatRequestH\x00R\fheartbeatReq\x12?\n" +
	"\x0eheartbeat_resp\x18\n" +
	" \x01(\v2\x16.gmq.HeartbeatResponseH\x00R\rheartbeatResp\x123\n" +
	"\n" +
	"error_resp\x18\v \x01(\v2\x12.gmq.ErrorResponseH\x00R\terrorRespB\t\n" +
	"\apayload\"\xc7\x02\n" +
	"\x0ePublishRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12#\n" +
	"\rpartition_key\x18\x03 \x01(\tR\fpartitionKey\x12!\n" +
	"\fpartition_id\x18\x04 \x01(\x05R\vpartitionId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12C\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2#.gmq.PublishRequest.PropertiesEntryR\n" +
	"properties\x12\x1a\n" +
	"\x03qos\x18\a \x01(\x0e2\b.gmq.QoSR\x03qos\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x0fPublishResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x05 \x01(\x05R\vpartitionId\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\x92\x02\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12%\n" +
	"\x0econsumer_group\x18\x03 \x01(\tR\rconsumerGroup\x12\x1f\n" +
	"\vconsumer_id\x18\x04 \x01(\tR\n" +
	"consumerId\x12\x1a\n" +
	"\x03qos\x18\x05 \x01(\x0e2\b.gmq.QoSR\x03qos\x12\x1e\n" +
	"\n" +
	"partitions\x18\x06 \x03(\x05R\n" +
	"partitions\x12(\n" +
	"\x10pull_interval_ms\x18\a \x01(\x05R\x0epullIntervalMs\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\"k\n" +
	"\x12CreateTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x01(\x05R\n" +
	"partitions\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"T\n" +
	"\x13CreateTopicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa2\x01\n" +
	"\x11SubscribeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12/\n" +
	"\x13assigned_partitions\x18\x03 \x03(\x05R\x12assignedPartitions\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xd8\x02\n" +
	"\x0eConsumeMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\x05R\vpartitionId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12C\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2#.gmq.ConsumeMessage.PropertiesEntryR\n" +
	"properties\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\x03qos\x18\b \x01(\x0e2\b.gmq.QoSR\x03qos\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x01\n" +
	"\n" +
	"AckRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x04 \x01(\x05R\vpartitionId\x12%\n" +
	"\x0econsumer_group\x18\x05 \x01(\tR\rconsumerGroup\x12\x1f\n" +
	"\vconsumer_id\x18\x06 \x01(\tR\n" +
	"consumerId\x12\x16\n" +
	"\x06offset\x18\a \x01(\x03R\x06offset\"k\n" +
	"\vAckResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"Z\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x82\x03\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMESSAGE_TYPE_PUBLISH_REQUEST\x10\x01\x12!\n" +
	"\x1dMESSAGE_TYPE_PUBLISH_RESPONSE\x10\x02\x12\"\n" +
	"\x1eMESSAGE_TYPE_SUBSCRIBE_REQUEST\x10\x03\x12#\n" +
	"\x1fMESSAGE_TYPE_SUBSCRIBE_RESPONSE\x10\x04\x12 \n" +
	"\x1cMESSAGE_TYPE_CONSUME_MESSAGE\x10\x05\x12\x1c\n" +
	"\x18MESSAGE_TYPE_ACK_REQUEST\x10\x06\x12\x1d\n" +
	"\x19MESSAGE_TYPE_ACK_RESPONSE\x10\a\x12\"\n" +
	"\x1eMESSAGE_TYPE_HEARTBEAT_REQUEST\x10\b\x12#\n" +
	"\x1fMESSAGE_TYPE_HEARTBEAT_RESPONSE\x10\t\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_ERROR_RESPONSE\x10\n" +
	"*G\n" +
	"\x03QoS\x12\x13\n" +
	"\x0fQOS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10QOS_AT_MOST_ONCE\x10\x01\x12\x15\n" +
	"\x11QOS_AT_LEAST_ONCE\x10\x022\x84\x01\n" +
	"\n" +
	"GMQService\x124\n" +
	"\x06Stream\x12\x12.gmq.StreamMessage\x1a\x12.gmq.StreamMessage(\x010\x01\x12@\n" +
	"\vCreateTopic\x12\x17.gmq.CreateTopicRequest\x1a\x18.gmq.CreateTopicResponseB!Z\x1fgithub.com/chowyu12/gmq/proto;gmqb\x06proto3"

var (
	file_proto_gmq_proto_rawDescOnce sync.Once
	file_proto_gmq_proto_rawDescData []byte
)

func file_proto_gmq_proto_rawDescGZIP() []byte {
	file_proto_gmq_proto_rawDescOnce.Do(func() {
		file_proto_gmq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gmq_proto_rawDesc), len(file_proto_gmq_proto_rawDesc)))
	})
	return file_proto_gmq_proto_rawDescData
}

var file_proto_gmq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_gmq_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_gmq_proto_goTypes = []any{
	(MessageType)(0),            // 0: gmq.MessageType
	(QoS)(0),                    // 1: gmq.QoS
	(*StreamMessage)(nil),       // 2: gmq.StreamMessage
	(*PublishRequest)(nil),      // 3: gmq.PublishRequest
	(*PublishResponse)(nil),     // 4: gmq.PublishResponse
	(*SubscribeRequest)(nil),    // 5: gmq.SubscribeRequest
	(*CreateTopicRequest)(nil),  // 6: gmq.CreateTopicRequest
	(*CreateTopicResponse)(nil), // 7: gmq.CreateTopicResponse
	(*SubscribeResponse)(nil),   // 8: gmq.SubscribeResponse
	(*ConsumeMessage)(nil),      // 9: gmq.ConsumeMessage
	(*AckRequest)(nil),          // 10: gmq.AckRequest
	(*AckResponse)(nil),         // 11: gmq.AckResponse
	(*HeartbeatRequest)(nil),    // 12: gmq.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 13: gmq.HeartbeatResponse
	(*ErrorResponse)(nil),       // 14: gmq.ErrorResponse
	nil,                         // 15: gmq.PublishRequest.PropertiesEntry
	nil,                         // 16: gmq.ConsumeMessage.PropertiesEntry
}
var file_proto_gmq_proto_depIdxs = []int32{
	0,  // 0: gmq.StreamMessage.type:type_name -> gmq.MessageType
	3,  // 1: gmq.StreamMessage.publish_req:type_name -> gmq.PublishRequest
	4,  // 2: gmq.StreamMessage.publish_resp:type_name -> gmq.PublishResponse
	5,  // 3: gmq.StreamMessage.subscribe_req:type_name -> gmq.SubscribeRequest
	8,  // 4: gmq.StreamMessage.subscribe_resp:type_name -> gmq.SubscribeResponse
	9,  // 5: gmq.StreamMessage.consume_msg:type_name -> gmq.ConsumeMessage
	10, // 6: gmq.StreamMessage.ack_req:type_name -> gmq.AckRequest
	11, // 7: gmq.StreamMessage.ack_resp:type_name -> gmq.AckResponse
	12, // 8: gmq.StreamMessage.heartbeat_req:type_name -> gmq.HeartbeatRequest
	13, // 9: gmq.StreamMessage.heartbeat_resp:type_name -> gmq.HeartbeatResponse
	14, // 10: gmq.StreamMessage.error_resp:type_name -> gmq.ErrorResponse
	15, // 11: gmq.PublishRequest.properties:type_name -> gmq.PublishRequest.PropertiesEntry
	1,  // 12: gmq.PublishRequest.qos:type_name -> gmq.QoS
	1,  // 13: gmq.SubscribeRequest.qos:type_name -> gmq.QoS
	16, // 14: gmq.ConsumeMessage.properties:type_name -> gmq.ConsumeMessage.PropertiesEntry
	1,  // 15: gmq.ConsumeMessage.qos:type_name -> gmq.QoS
	2,  // 16: gmq.GMQService.Stream:input_type -> gmq.StreamMessage
	6,  // 17: gmq.GMQService.CreateTopic:input_type -> gmq.CreateTopicRequest
	2,  // 18: gmq.GMQService.Stream:output_type -> gmq.StreamMessage
	7,  // 19: gmq.GMQService.CreateTopic:output_type -> gmq.CreateTopicResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_gmq_proto_init() }
func file_proto_gmq_proto_init() {
	if File_proto_gmq_proto != nil {
		return
	}
	file_proto_gmq_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamMessage_PublishReq)(nil),
		(*StreamMessage_PublishResp)(nil),
		(*StreamMessage_SubscribeReq)(nil),
		(*StreamMessage_SubscribeResp)(nil),
		(*StreamMessage_ConsumeMsg)(nil),
		(*StreamMessage_AckReq)(nil),
		(*StreamMessage_AckResp)(nil),
		(*StreamMessage_HeartbeatReq)(nil),
		(*StreamMessage_HeartbeatResp)(nil),
		(*StreamMessage_ErrorResp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gmq_proto_rawDesc), len(file_proto_gmq_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gmq_proto_goTypes,
		DependencyIndexes: file_proto_gmq_proto_depIdxs,
		EnumInfos:         file_proto_gmq_proto_enumTypes,
		MessageInfos:      file_proto_gmq_proto_msgTypes,
	}.Build()
	File_proto_gmq_proto = out.File
	file_proto_gmq_proto_goTypes = nil
	file_proto_gmq_proto_depIdxs = nil
}
