// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/gmq.proto

package gmq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message type
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	// Publish message request
	MessageType_MESSAGE_TYPE_PUBLISH_REQUEST MessageType = 1
	// Publish message response
	MessageType_MESSAGE_TYPE_PUBLISH_RESPONSE MessageType = 2
	// Subscribe request
	MessageType_MESSAGE_TYPE_SUBSCRIBE_REQUEST MessageType = 3
	// Subscribe response
	MessageType_MESSAGE_TYPE_SUBSCRIBE_RESPONSE MessageType = 4
	// Consume message push
	MessageType_MESSAGE_TYPE_CONSUME_MESSAGE MessageType = 5
	// Message acknowledgment request
	MessageType_MESSAGE_TYPE_ACK_REQUEST MessageType = 6
	// Message acknowledgment response
	MessageType_MESSAGE_TYPE_ACK_RESPONSE MessageType = 7
	// Heartbeat request
	MessageType_MESSAGE_TYPE_HEARTBEAT_REQUEST MessageType = 8
	// Heartbeat response
	MessageType_MESSAGE_TYPE_HEARTBEAT_RESPONSE MessageType = 9
	// Error response
	MessageType_MESSAGE_TYPE_ERROR_RESPONSE MessageType = 10
	// Client-initiated pull request
	MessageType_MESSAGE_TYPE_PULL_REQUEST MessageType = 11
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_PUBLISH_REQUEST",
		2:  "MESSAGE_TYPE_PUBLISH_RESPONSE",
		3:  "MESSAGE_TYPE_SUBSCRIBE_REQUEST",
		4:  "MESSAGE_TYPE_SUBSCRIBE_RESPONSE",
		5:  "MESSAGE_TYPE_CONSUME_MESSAGE",
		6:  "MESSAGE_TYPE_ACK_REQUEST",
		7:  "MESSAGE_TYPE_ACK_RESPONSE",
		8:  "MESSAGE_TYPE_HEARTBEAT_REQUEST",
		9:  "MESSAGE_TYPE_HEARTBEAT_RESPONSE",
		10: "MESSAGE_TYPE_ERROR_RESPONSE",
		11: "MESSAGE_TYPE_PULL_REQUEST",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":        0,
		"MESSAGE_TYPE_PUBLISH_REQUEST":    1,
		"MESSAGE_TYPE_PUBLISH_RESPONSE":   2,
		"MESSAGE_TYPE_SUBSCRIBE_REQUEST":  3,
		"MESSAGE_TYPE_SUBSCRIBE_RESPONSE": 4,
		"MESSAGE_TYPE_CONSUME_MESSAGE":    5,
		"MESSAGE_TYPE_ACK_REQUEST":        6,
		"MESSAGE_TYPE_ACK_RESPONSE":       7,
		"MESSAGE_TYPE_HEARTBEAT_REQUEST":  8,
		"MESSAGE_TYPE_HEARTBEAT_RESPONSE": 9,
		"MESSAGE_TYPE_ERROR_RESPONSE":     10,
		"MESSAGE_TYPE_PULL_REQUEST":       11,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gmq_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_gmq_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{0}
}

// Stream message wrapper
type StreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message type
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=gmq.MessageType" json:"type,omitempty"`
	// Specific message content (select corresponding field based on type)
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamMessage_PublishReq
	//	*StreamMessage_PublishResp
	//	*StreamMessage_SubscribeReq
	//	*StreamMessage_SubscribeResp
	//	*StreamMessage_ConsumeMsg
	//	*StreamMessage_AckReq
	//	*StreamMessage_AckResp
	//	*StreamMessage_HeartbeatReq
	//	*StreamMessage_HeartbeatResp
	//	*StreamMessage_ErrorResp
	//	*StreamMessage_PullReq
	Payload       isStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_proto_gmq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{0}
}

func (x *StreamMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *StreamMessage) GetPayload() isStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamMessage) GetPublishReq() *PublishRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_PublishReq); ok {
			return x.PublishReq
		}
	}
	return nil
}

func (x *StreamMessage) GetPublishResp() *PublishResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_PublishResp); ok {
			return x.PublishResp
		}
	}
	return nil
}

func (x *StreamMessage) GetSubscribeReq() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_SubscribeReq); ok {
			return x.SubscribeReq
		}
	}
	return nil
}

func (x *StreamMessage) GetSubscribeResp() *SubscribeResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_SubscribeResp); ok {
			return x.SubscribeResp
		}
	}
	return nil
}

func (x *StreamMessage) GetConsumeMsg() *ConsumeMessage {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_ConsumeMsg); ok {
			return x.ConsumeMsg
		}
	}
	return nil
}

func (x *StreamMessage) GetAckReq() *AckRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_AckReq); ok {
			return x.AckReq
		}
	}
	return nil
}

func (x *StreamMessage) GetAckResp() *AckResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_AckResp); ok {
			return x.AckResp
		}
	}
	return nil
}

func (x *StreamMessage) GetHeartbeatReq() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_HeartbeatReq); ok {
			return x.HeartbeatReq
		}
	}
	return nil
}

func (x *StreamMessage) GetHeartbeatResp() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_HeartbeatResp); ok {
			return x.HeartbeatResp
		}
	}
	return nil
}

func (x *StreamMessage) GetErrorResp() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_ErrorResp); ok {
			return x.ErrorResp
		}
	}
	return nil
}

func (x *StreamMessage) GetPullReq() *PullRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_PullReq); ok {
			return x.PullReq
		}
	}
	return nil
}

type isStreamMessage_Payload interface {
	isStreamMessage_Payload()
}

type StreamMessage_PublishReq struct {
	PublishReq *PublishRequest `protobuf:"bytes,2,opt,name=publish_req,json=publishReq,proto3,oneof"`
}

type StreamMessage_PublishResp struct {
	PublishResp *PublishResponse `protobuf:"bytes,3,opt,name=publish_resp,json=publishResp,proto3,oneof"`
}

type StreamMessage_SubscribeReq struct {
	SubscribeReq *SubscribeRequest `protobuf:"bytes,4,opt,name=subscribe_req,json=subscribeReq,proto3,oneof"`
}

type StreamMessage_SubscribeResp struct {
	SubscribeResp *SubscribeResponse `protobuf:"bytes,5,opt,name=subscribe_resp,json=subscribeResp,proto3,oneof"`
}

type StreamMessage_ConsumeMsg struct {
	ConsumeMsg *ConsumeMessage `protobuf:"bytes,6,opt,name=consume_msg,json=consumeMsg,proto3,oneof"`
}

type StreamMessage_AckReq struct {
	AckReq *AckRequest `protobuf:"bytes,7,opt,name=ack_req,json=ackReq,proto3,oneof"`
}

type StreamMessage_AckResp struct {
	AckResp *AckResponse `protobuf:"bytes,8,opt,name=ack_resp,json=ackResp,proto3,oneof"`
}

type StreamMessage_HeartbeatReq struct {
	HeartbeatReq *HeartbeatRequest `protobuf:"bytes,9,opt,name=heartbeat_req,json=heartbeatReq,proto3,oneof"`
}

type StreamMessage_HeartbeatResp struct {
	HeartbeatResp *HeartbeatResponse `protobuf:"bytes,10,opt,name=heartbeat_resp,json=heartbeatResp,proto3,oneof"`
}

type StreamMessage_ErrorResp struct {
	ErrorResp *ErrorResponse `protobuf:"bytes,11,opt,name=error_resp,json=errorResp,proto3,oneof"`
}

type StreamMessage_PullReq struct {
	PullReq *PullRequest `protobuf:"bytes,12,opt,name=pull_req,json=pullReq,proto3,oneof"`
}

func (*StreamMessage_PublishReq) isStreamMessage_Payload() {}

func (*StreamMessage_PublishResp) isStreamMessage_Payload() {}

func (*StreamMessage_SubscribeReq) isStreamMessage_Payload() {}

func (*StreamMessage_SubscribeResp) isStreamMessage_Payload() {}

func (*StreamMessage_ConsumeMsg) isStreamMessage_Payload() {}

func (*StreamMessage_AckReq) isStreamMessage_Payload() {}

func (*StreamMessage_AckResp) isStreamMessage_Payload() {}

func (*StreamMessage_HeartbeatReq) isStreamMessage_Payload() {}

func (*StreamMessage_HeartbeatResp) isStreamMessage_Payload() {}

func (*StreamMessage_ErrorResp) isStreamMessage_Payload() {}

func (*StreamMessage_PullReq) isStreamMessage_Payload() {}

// Publish message request (supports batch)
type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Message list
	Items         []*PublishItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_gmq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PublishRequest) GetItems() []*PublishItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PublishItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic name
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// Partition key (used to determine partition)
	PartitionKey string `protobuf:"bytes,2,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	// Specify partition ID (optional, priority higher than partition_key)
	PartitionId *int32 `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3,oneof" json:"partition_id,omitempty"`
	// Message body
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Message properties
	Properties map[string]string `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Producer idempotency support
	ProducerId     string `protobuf:"bytes,6,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	SequenceNumber int64  `protobuf:"varint,7,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishItem) Reset() {
	*x = PublishItem{}
	mi := &file_proto_gmq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishItem) ProtoMessage() {}

func (x *PublishItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishItem.ProtoReflect.Descriptor instead.
func (*PublishItem) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{2}
}

func (x *PublishItem) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishItem) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *PublishItem) GetPartitionId() int32 {
	if x != nil && x.PartitionId != nil {
		return *x.PartitionId
	}
	return 0
}

func (x *PublishItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishItem) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *PublishItem) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *PublishItem) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// Publish message response (supports batch)
type PublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Result list
	Results       []*PublishResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_gmq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{3}
}

func (x *PublishResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PublishResponse) GetResults() []*PublishResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type PublishResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message ID
	MessageId string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Topic name
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// Actual partition ID
	PartitionId int32 `protobuf:"varint,4,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Error message
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResult) Reset() {
	*x = PublishResult{}
	mi := &file_proto_gmq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResult) ProtoMessage() {}

func (x *PublishResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResult.ProtoReflect.Descriptor instead.
func (*PublishResult) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{4}
}

func (x *PublishResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResult) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PublishResult) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishResult) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PublishResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Subscribe request
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Topic name
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// Consumer group name
	ConsumerGroup string `protobuf:"bytes,3,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	// Consumer ID
	ConsumerId    string `protobuf:"bytes,4,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_gmq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

// Subscribe response
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Whether successful
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Error message
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_proto_gmq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscribeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Consume message (supports batch push)
type ConsumeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MessageItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeMessage) Reset() {
	*x = ConsumeMessage{}
	mi := &file_proto_gmq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeMessage) ProtoMessage() {}

func (x *ConsumeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeMessage.ProtoReflect.Descriptor instead.
func (*ConsumeMessage) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{7}
}

func (x *ConsumeMessage) GetItems() []*MessageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MessageItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message ID
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Topic name
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// Partition ID
	PartitionId int32 `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Offset
	Offset int64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// Message body
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// Message properties
	Properties map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timestamp
	Timestamp int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Partition routing key
	Key           string `protobuf:"bytes,8,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_proto_gmq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{8}
}

func (x *MessageItem) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageItem) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MessageItem) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *MessageItem) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MessageItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessageItem) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *MessageItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Message acknowledgment request (supports batch acknowledgment)
type AckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Consumer group
	ConsumerGroup string `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	// Consumer ID
	ConsumerId string `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// Acknowledgment item list
	Items         []*AckItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_gmq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{9}
}

func (x *AckRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AckRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *AckRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *AckRequest) GetItems() []*AckItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AckItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId   int32                  `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckItem) Reset() {
	*x = AckItem{}
	mi := &file_proto_gmq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckItem) ProtoMessage() {}

func (x *AckItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckItem.ProtoReflect.Descriptor instead.
func (*AckItem) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{10}
}

func (x *AckItem) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckItem) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *AckItem) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AckItem) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Message acknowledgment response
type AckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Whether successful
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Error message
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_gmq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{11}
}

func (x *AckResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Heartbeat request
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consumer ID
	ConsumerId string `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// Consumer group
	ConsumerGroup string `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_gmq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *HeartbeatRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

// Heartbeat response
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_gmq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Error response
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Error message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_gmq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Client-initiated pull message request
type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_proto_gmq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gmq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_proto_gmq_proto_rawDescGZIP(), []int{15}
}

func (x *PullRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_gmq_proto protoreflect.FileDescriptor

const file_proto_gmq_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/gmq.proto\x12\x03gmq\"\xa8\x05\n" +
	"\rStreamMessage\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.gmq.MessageTypeR\x04type\x126\n" +
	"\vpublish_req\x18\x02 \x01(\v2\x13.gmq.PublishRequestH\x00R\n" +
	"publishReq\x129\n" +
	"\fpublish_resp\x18\x03 \x01(\v2\x14.gmq.PublishResponseH\x00R\vpublishResp\x12<\n" +
	"\rsubscribe_req\x18\x04 \x01(\v2\x15.gmq.SubscribeRequestH\x00R\fsubscribeReq\x12?\n" +
	"\x0esubscribe_resp\x18\x05 \x01(\v2\x16.gmq.SubscribeResponseH\x00R\rsubscribeResp\x126\n" +
	"\vconsume_msg\x18\x06 \x01(\v2\x13.gmq.ConsumeMessageH\x00R\n" +
	"consumeMsg\x12*\n" +
	"\aack_req\x18\a \x01(\v2\x0f.gmq.AckRequestH\x00R\x06ackReq\x12-\n" +
	"\back_resp\x18\b \x01(\v2\x10.gmq.AckResponseH\x00R\aackResp\x12<\n" +
	"\rheartbeat_req\x18\t \x01(\v2\x15.gmq.HeartbeatRequestH\x00R\fheartbeatReq\x12?\n" +
	"\x0eheartbeat_resp\x18\n" +
	" \x01(\v2\x16.gmq.HeartbeatResponseH\x00R\rheartbeatResp\x123\n" +
	"\n" +
	"error_resp\x18\v \x01(\v2\x12.gmq.ErrorResponseH\x00R\terrorResp\x12-\n" +
	"\bpull_req\x18\f \x01(\v2\x10.gmq.PullRequestH\x00R\apullReqB\t\n" +
	"\apayload\"W\n" +
	"\x0ePublishRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12&\n" +
	"\x05items\x18\x02 \x03(\v2\x10.gmq.PublishItemR\x05items\"\xe6\x02\n" +
	"\vPublishItem\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12#\n" +
	"\rpartition_key\x18\x02 \x01(\tR\fpartitionKey\x12&\n" +
	"\fpartition_id\x18\x03 \x01(\x05H\x00R\vpartitionId\x88\x01\x01\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12@\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2 .gmq.PublishItem.PropertiesEntryR\n" +
	"properties\x12\x1f\n" +
	"\vproducer_id\x18\x06 \x01(\tR\n" +
	"producerId\x12'\n" +
	"\x0fsequence_number\x18\a \x01(\x03R\x0esequenceNumber\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_partition_id\"^\n" +
	"\x0fPublishResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12,\n" +
	"\aresults\x18\x02 \x03(\v2\x12.gmq.PublishResultR\aresults\"\xa6\x01\n" +
	"\rPublishResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x04 \x01(\x05R\vpartitionId\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x8f\x01\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12%\n" +
	"\x0econsumer_group\x18\x03 \x01(\tR\rconsumerGroup\x12\x1f\n" +
	"\vconsumer_id\x18\x04 \x01(\tR\n" +
	"consumerId\"q\n" +
	"\x11SubscribeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"8\n" +
	"\x0eConsumeMessage\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.gmq.MessageItemR\x05items\"\xc8\x02\n" +
	"\vMessageItem\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\x05R\vpartitionId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12@\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2 .gmq.MessageItem.PropertiesEntryR\n" +
	"properties\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03key\x18\b \x01(\tR\x03key\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\n" +
	"AckRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\x12\"\n" +
	"\x05items\x18\x04 \x03(\v2\f.gmq.AckItemR\x05items\"y\n" +
	"\aAckItem\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"k\n" +
	"\vAckResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"Z\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\vPullRequest\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04*\xa1\x03\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMESSAGE_TYPE_PUBLISH_REQUEST\x10\x01\x12!\n" +
	"\x1dMESSAGE_TYPE_PUBLISH_RESPONSE\x10\x02\x12\"\n" +
	"\x1eMESSAGE_TYPE_SUBSCRIBE_REQUEST\x10\x03\x12#\n" +
	"\x1fMESSAGE_TYPE_SUBSCRIBE_RESPONSE\x10\x04\x12 \n" +
	"\x1cMESSAGE_TYPE_CONSUME_MESSAGE\x10\x05\x12\x1c\n" +
	"\x18MESSAGE_TYPE_ACK_REQUEST\x10\x06\x12\x1d\n" +
	"\x19MESSAGE_TYPE_ACK_RESPONSE\x10\a\x12\"\n" +
	"\x1eMESSAGE_TYPE_HEARTBEAT_REQUEST\x10\b\x12#\n" +
	"\x1fMESSAGE_TYPE_HEARTBEAT_RESPONSE\x10\t\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_ERROR_RESPONSE\x10\n" +
	"\x12\x1d\n" +
	"\x19MESSAGE_TYPE_PULL_REQUEST\x10\v2B\n" +
	"\n" +
	"GMQService\x124\n" +
	"\x06Stream\x12\x12.gmq.StreamMessage\x1a\x12.gmq.StreamMessage(\x010\x01B#Z!github.com/chowyu12/gmq/proto;gmqb\x06proto3"

var (
	file_proto_gmq_proto_rawDescOnce sync.Once
	file_proto_gmq_proto_rawDescData []byte
)

func file_proto_gmq_proto_rawDescGZIP() []byte {
	file_proto_gmq_proto_rawDescOnce.Do(func() {
		file_proto_gmq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gmq_proto_rawDesc), len(file_proto_gmq_proto_rawDesc)))
	})
	return file_proto_gmq_proto_rawDescData
}

var file_proto_gmq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gmq_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_gmq_proto_goTypes = []any{
	(MessageType)(0),          // 0: gmq.MessageType
	(*StreamMessage)(nil),     // 1: gmq.StreamMessage
	(*PublishRequest)(nil),    // 2: gmq.PublishRequest
	(*PublishItem)(nil),       // 3: gmq.PublishItem
	(*PublishResponse)(nil),   // 4: gmq.PublishResponse
	(*PublishResult)(nil),     // 5: gmq.PublishResult
	(*SubscribeRequest)(nil),  // 6: gmq.SubscribeRequest
	(*SubscribeResponse)(nil), // 7: gmq.SubscribeResponse
	(*ConsumeMessage)(nil),    // 8: gmq.ConsumeMessage
	(*MessageItem)(nil),       // 9: gmq.MessageItem
	(*AckRequest)(nil),        // 10: gmq.AckRequest
	(*AckItem)(nil),           // 11: gmq.AckItem
	(*AckResponse)(nil),       // 12: gmq.AckResponse
	(*HeartbeatRequest)(nil),  // 13: gmq.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 14: gmq.HeartbeatResponse
	(*ErrorResponse)(nil),     // 15: gmq.ErrorResponse
	(*PullRequest)(nil),       // 16: gmq.PullRequest
	nil,                       // 17: gmq.PublishItem.PropertiesEntry
	nil,                       // 18: gmq.MessageItem.PropertiesEntry
}
var file_proto_gmq_proto_depIdxs = []int32{
	0,  // 0: gmq.StreamMessage.type:type_name -> gmq.MessageType
	2,  // 1: gmq.StreamMessage.publish_req:type_name -> gmq.PublishRequest
	4,  // 2: gmq.StreamMessage.publish_resp:type_name -> gmq.PublishResponse
	6,  // 3: gmq.StreamMessage.subscribe_req:type_name -> gmq.SubscribeRequest
	7,  // 4: gmq.StreamMessage.subscribe_resp:type_name -> gmq.SubscribeResponse
	8,  // 5: gmq.StreamMessage.consume_msg:type_name -> gmq.ConsumeMessage
	10, // 6: gmq.StreamMessage.ack_req:type_name -> gmq.AckRequest
	12, // 7: gmq.StreamMessage.ack_resp:type_name -> gmq.AckResponse
	13, // 8: gmq.StreamMessage.heartbeat_req:type_name -> gmq.HeartbeatRequest
	14, // 9: gmq.StreamMessage.heartbeat_resp:type_name -> gmq.HeartbeatResponse
	15, // 10: gmq.StreamMessage.error_resp:type_name -> gmq.ErrorResponse
	16, // 11: gmq.StreamMessage.pull_req:type_name -> gmq.PullRequest
	3,  // 12: gmq.PublishRequest.items:type_name -> gmq.PublishItem
	17, // 13: gmq.PublishItem.properties:type_name -> gmq.PublishItem.PropertiesEntry
	5,  // 14: gmq.PublishResponse.results:type_name -> gmq.PublishResult
	9,  // 15: gmq.ConsumeMessage.items:type_name -> gmq.MessageItem
	18, // 16: gmq.MessageItem.properties:type_name -> gmq.MessageItem.PropertiesEntry
	11, // 17: gmq.AckRequest.items:type_name -> gmq.AckItem
	1,  // 18: gmq.GMQService.Stream:input_type -> gmq.StreamMessage
	1,  // 19: gmq.GMQService.Stream:output_type -> gmq.StreamMessage
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_gmq_proto_init() }
func file_proto_gmq_proto_init() {
	if File_proto_gmq_proto != nil {
		return
	}
	file_proto_gmq_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamMessage_PublishReq)(nil),
		(*StreamMessage_PublishResp)(nil),
		(*StreamMessage_SubscribeReq)(nil),
		(*StreamMessage_SubscribeResp)(nil),
		(*StreamMessage_ConsumeMsg)(nil),
		(*StreamMessage_AckReq)(nil),
		(*StreamMessage_AckResp)(nil),
		(*StreamMessage_HeartbeatReq)(nil),
		(*StreamMessage_HeartbeatResp)(nil),
		(*StreamMessage_ErrorResp)(nil),
		(*StreamMessage_PullReq)(nil),
	}
	file_proto_gmq_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gmq_proto_rawDesc), len(file_proto_gmq_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gmq_proto_goTypes,
		DependencyIndexes: file_proto_gmq_proto_depIdxs,
		EnumInfos:         file_proto_gmq_proto_enumTypes,
		MessageInfos:      file_proto_gmq_proto_msgTypes,
	}.Build()
	File_proto_gmq_proto = out.File
	file_proto_gmq_proto_goTypes = nil
	file_proto_gmq_proto_depIdxs = nil
}
