// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/gmq.proto

package gmq

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GMQService_Stream_FullMethodName      = "/gmq.GMQService/Stream"
	GMQService_CreateTopic_FullMethodName = "/gmq.GMQService/CreateTopic"
)

// GMQServiceClient is the client API for GMQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GMQ 消息队列服务
type GMQServiceClient interface {
	// 双向流：生产和消费消息
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error)
	// 管理接口：手动创建 Topic
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
}

type gMQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGMQServiceClient(cc grpc.ClientConnInterface) GMQServiceClient {
	return &gMQServiceClient{cc}
}

func (c *gMQServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GMQService_ServiceDesc.Streams[0], GMQService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GMQService_StreamClient = grpc.BidiStreamingClient[StreamMessage, StreamMessage]

func (c *gMQServiceClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, GMQService_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GMQServiceServer is the server API for GMQService service.
// All implementations must embed UnimplementedGMQServiceServer
// for forward compatibility.
//
// GMQ 消息队列服务
type GMQServiceServer interface {
	// 双向流：生产和消费消息
	Stream(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error
	// 管理接口：手动创建 Topic
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	mustEmbedUnimplementedGMQServiceServer()
}

// UnimplementedGMQServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGMQServiceServer struct{}

func (UnimplementedGMQServiceServer) Stream(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGMQServiceServer) CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedGMQServiceServer) mustEmbedUnimplementedGMQServiceServer() {}
func (UnimplementedGMQServiceServer) testEmbeddedByValue()                    {}

// UnsafeGMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GMQServiceServer will
// result in compilation errors.
type UnsafeGMQServiceServer interface {
	mustEmbedUnimplementedGMQServiceServer()
}

func RegisterGMQServiceServer(s grpc.ServiceRegistrar, srv GMQServiceServer) {
	// If the following call pancis, it indicates UnimplementedGMQServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GMQService_ServiceDesc, srv)
}

func _GMQService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GMQServiceServer).Stream(&grpc.GenericServerStream[StreamMessage, StreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GMQService_StreamServer = grpc.BidiStreamingServer[StreamMessage, StreamMessage]

func _GMQService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMQServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GMQService_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMQServiceServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GMQService_ServiceDesc is the grpc.ServiceDesc for GMQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GMQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gmq.GMQService",
	HandlerType: (*GMQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTopic",
			Handler:    _GMQService_CreateTopic_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _GMQService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gmq.proto",
}
