// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/gmq.proto

package gmq

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GMQService_Stream_FullMethodName = "/gmq.GMQService/Stream"
)

// GMQServiceClient is the client API for GMQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GMQ Message Queue Service
type GMQServiceClient interface {
	// Bidirectional stream: produce and consume messages
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error)
}

type gMQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGMQServiceClient(cc grpc.ClientConnInterface) GMQServiceClient {
	return &gMQServiceClient{cc}
}

func (c *gMQServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GMQService_ServiceDesc.Streams[0], GMQService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GMQService_StreamClient = grpc.BidiStreamingClient[StreamMessage, StreamMessage]

// GMQServiceServer is the server API for GMQService service.
// All implementations must embed UnimplementedGMQServiceServer
// for forward compatibility.
//
// GMQ Message Queue Service
type GMQServiceServer interface {
	// Bidirectional stream: produce and consume messages
	Stream(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error
	mustEmbedUnimplementedGMQServiceServer()
}

// UnimplementedGMQServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGMQServiceServer struct{}

func (UnimplementedGMQServiceServer) Stream(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGMQServiceServer) mustEmbedUnimplementedGMQServiceServer() {}
func (UnimplementedGMQServiceServer) testEmbeddedByValue()                    {}

// UnsafeGMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GMQServiceServer will
// result in compilation errors.
type UnsafeGMQServiceServer interface {
	mustEmbedUnimplementedGMQServiceServer()
}

func RegisterGMQServiceServer(s grpc.ServiceRegistrar, srv GMQServiceServer) {
	// If the following call pancis, it indicates UnimplementedGMQServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GMQService_ServiceDesc, srv)
}

func _GMQService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GMQServiceServer).Stream(&grpc.GenericServerStream[StreamMessage, StreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GMQService_StreamServer = grpc.BidiStreamingServer[StreamMessage, StreamMessage]

// GMQService_ServiceDesc is the grpc.ServiceDesc for GMQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GMQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gmq.GMQService",
	HandlerType: (*GMQServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _GMQService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gmq.proto",
}
